//! Generated API assembly bootstrap for sdkwork-shop.
//! Regenerated by pnpm api:assembly:materialize.
//!
//! Multi-surface merges mount shared infrastructure routes once at the assembly layer
//! so `/healthz`, `/livez`, `/readyz`, and `/metrics` are not duplicated per surface.

use axum::Router;
use sdkwork_shop_service_host::ShopServiceHost;
use std::sync::Arc;

pub struct ApiAssembly {
    pub router: Router,
}

pub async fn assemble_api_router(host: Arc<ShopServiceHost>) -> ApiAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_shop_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_shop_backend_api::gateway_mount(host.clone()).await);
    ApiAssembly { router }
}
