//! Generated gateway bootstrap for sdkwork-shop.
//! Regenerated by pnpm gateway:assembly:materialize when bootstrap contains todo!().

use axum::Router;
use sdkwork_shop_service_host::ShopServiceHost;
use std::sync::Arc;

pub struct ApplicationAssembly {
    pub router: Router,
}

pub async fn assemble_application_router(host: Arc<ShopServiceHost>) -> ApplicationAssembly {
    let mut router = Router::new();
    router = router.merge(sdkwork_routes_shop_app_api::gateway_mount(host.clone()).await);
    router = router.merge(sdkwork_routes_shop_backend_api::gateway_mount(host).await);
    ApplicationAssembly { router }
}
